# Generated by Django 3.0.2 on 2020-02-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostandFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='帖子内容')),
                ('itemtype', models.CharField(choices=[('L', '遗失'), ('F', '拾取')], max_length=20, null=True, verbose_name='帖子类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.BigIntegerField(default=0, null=True, verbose_name='点赞数')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '失物招领帖子',
                'verbose_name_plural': '失物招领帖子',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfound.LostandFound')),
            ],
            options={
                'verbose_name': '失物招领的照片',
                'verbose_name_plural': '失物招领的照片',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_which_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfound.LostandFound')),
                ('to_which_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='失物招领评论接受者', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='失物招领评论发送者', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '失物招领的评论',
                'verbose_name_plural': '失物招领的评论',
            },
        ),
    ]
