# Generated by Django 3.0.2 on 2020-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '失物招领的评论',
                'verbose_name_plural': '失物招领的评论',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': '二手交易的图片',
                'verbose_name_plural': '二手交易的图片',
            },
        ),
        migrations.CreateModel(
            name='SecondHandTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='帖子内容')),
                ('itemtype', models.CharField(choices=[('W', '想要'), ('S', '出售')], max_length=20, null=True, verbose_name='帖子类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.BigIntegerField(default=0, null=True, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '二手交易帖子',
                'verbose_name_plural': '二手交易帖子',
            },
        ),
    ]
