# Generated by Django 3.0.2 on 2020-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('content', models.TextField(max_length=4000, verbose_name='帖子内容')),
                ('time_lab', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('detail_url', models.CharField(blank=True, max_length=254, null=True, verbose_name='公司链接')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='职位描述')),
                ('salary_lo', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='最低薪水')),
                ('salary_hi', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='最高薪水')),
                ('edu_require', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='学历要求')),
                ('exp_require', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='经历要求')),
                ('place', models.CharField(default='', max_length=300, verbose_name='地点')),
                ('want_num', models.CharField(default='', max_length=300, verbose_name='招聘人数')),
            ],
            options={
                'verbose_name': '招聘帖子',
                'verbose_name_plural': '招聘帖子',
            },
        ),
    ]
