# Generated by Django 2.1 on 2019-04-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000, verbose_name='评论内容')),
                ('created_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('companylink', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': '招聘评论',
                'verbose_name_plural': '招聘评论',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': '招聘照片',
                'verbose_name_plural': '招聘照片',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('content', models.TextField(blank=True, max_length=4000, null=True, verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.BigIntegerField(default=0, null=True, verbose_name='点赞数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='招聘发帖者', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '招聘帖子',
                'verbose_name_plural': '招聘帖子',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_which_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_which_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='招聘发送给谁的评论', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='招聘评论者', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
