# Generated by Django 2.2.4 on 2019-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitpost',
            old_name='salary_high',
            new_name='salary_hi',
        ),
        migrations.RenameField(
            model_name='recruitpost',
            old_name='salary_low',
            new_name='salary_lo',
        ),
    ]
