# Generated by Django 3.0.2 on 2020-02-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('content', models.TextField(max_length=4000, verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.BigIntegerField(default=0, null=True, verbose_name='点赞数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myposts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '朋友圈帖子表',
                'verbose_name_plural': '朋友圈帖子表',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=1000, verbose_name='图片链接')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myimgs', to='friendcircle.FriendPost', verbose_name='所在帖子')),
            ],
            options={
                'verbose_name': '朋友圈照片表',
                'verbose_name_plural': '朋友圈照片表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='friendcircle.FriendPost', verbose_name='父帖')),
                ('to_which_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsecomment', to=settings.AUTH_USER_MODEL, verbose_name='回复的人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '朋友圈评论表',
                'verbose_name_plural': '朋友圈评论表',
            },
        ),
    ]
