# Generated by Django 2.1 on 2019-04-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendcircle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_which_commment',
        ),
        migrations.AddField(
            model_name='comment',
            name='to_which_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='发送给谁的评论', to=settings.AUTH_USER_MODEL),
        ),
    ]
