# Generated by Django 2.2.4 on 2019-08-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile_Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_background', models.CharField(blank=True, choices=[('U', '本科生'), ('M', '硕士'), ('P', '博士')], max_length=128, null=True, verbose_name='学历')),
                ('university', models.CharField(blank=True, max_length=128, null=True, verbose_name='所在学校')),
                ('imgurl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='头像url')),
                ('living_province', models.CharField(blank=True, max_length=128, null=True, verbose_name='居住省份')),
                ('living_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='居住城市')),
                ('identity', models.CharField(choices=[('1', '毕业生'), ('2', '在校生'), ('3', '企业账号')], default='2', max_length=128, verbose_name='用户身份')),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话号码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=128, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=128, null=True, verbose_name='年龄')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('birth_data', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('institution', models.CharField(blank=True, max_length=128, null=True, verbose_name='学院')),
                ('self_sign', models.CharField(blank=True, max_length=128, null=True, verbose_name='个性签名')),
                ('self_judgement', models.TextField(blank=True, null=True, verbose_name='自我评价')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mystuprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '在校生个人信息',
                'verbose_name_plural': '在校生个人信息',
            },
        ),
        migrations.CreateModel(
            name='User_Profile_Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('1', '毕业生'), ('2', '在校生'), ('3', '企业账号')], default='1', max_length=128, verbose_name='用户身份')),
                ('imgurl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='头像url')),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话号码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=128, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=128, null=True, verbose_name='年龄')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('birth_data', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('education_background', models.CharField(blank=True, choices=[('U', '本科生'), ('M', '硕士'), ('P', '博士')], max_length=128, null=True, verbose_name='学历')),
                ('university', models.CharField(blank=True, max_length=128, null=True, verbose_name='所在学校')),
                ('living_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='居住城市')),
                ('living_province', models.DateField(blank=True, max_length=128, null=True, verbose_name='居住省份')),
                ('school_period_start', models.DateField(blank=True, null=True, verbose_name='在校时间开始')),
                ('school_period_end', models.DateField(blank=True, null=True, verbose_name='在校时间结束')),
                ('honour', models.TextField(blank=True, max_length=1000, null=True, verbose_name='荣誉')),
                ('self_judgement', models.TextField(blank=True, max_length=1000, null=True, verbose_name='自我评价')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mygraduateproflie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '毕业生个人信息',
            },
        ),
        migrations.CreateModel(
            name='User_Profile_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(blank=True, max_length=1000, null=True, verbose_name='头像url')),
                ('identity', models.CharField(choices=[('1', '毕业生'), ('2', '在校生'), ('3', '企业账号')], default='3', max_length=128, verbose_name='用户身份')),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话号码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司名')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mycompanyprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '企业个人信息',
                'verbose_name_plural': '企业个人信息',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='文本内容')),
                ('headline', models.CharField(max_length=200, verbose_name='文本内容')),
                ('msgfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysendmsg', to=settings.AUTH_USER_MODEL, verbose_name='发信人')),
                ('msgto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myreceivemsg', to=settings.AUTH_USER_MODEL, verbose_name='收信人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_place', models.CharField(blank=True, max_length=128, null=True, verbose_name='工作单位')),
                ('job', models.CharField(blank=True, max_length=128, null=True, verbose_name='职业')),
                ('job_period_start', models.DateField(blank=True, null=True, verbose_name='就职时间')),
                ('job_period_end', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('job_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='工作城市')),
                ('job_salary', models.CharField(blank=True, max_length=128, null=True, verbose_name='年薪')),
                ('job_province', models.CharField(blank=True, max_length=128, null=True, verbose_name='省份')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myjobexp', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedby', models.ManyToManyField(blank=True, null=True, related_name='follwedby', to=settings.AUTH_USER_MODEL, verbose_name='谁的朋友')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fid', to=settings.AUTH_USER_MODEL, verbose_name='朋友的id')),
            ],
            options={
                'verbose_name': '关注对象表',
                'verbose_name_plural': '关注对象表',
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.DateField(blank=True, null=True, verbose_name='教育开始时间')),
                ('endtime', models.DateField(blank=True, null=True, verbose_name='教育结束时间')),
                ('school', models.CharField(blank=True, max_length=128, null=True, verbose_name='学校')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('educationbackground', models.CharField(blank=True, max_length=128, null=True, verbose_name='教育背景')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myeducationexp', to=settings.AUTH_USER_MODEL, verbose_name='用户教育经历')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
    ]
