# Generated by Django 3.0.2 on 2020-02-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='user_admin',
            options={'verbose_name': '管理员信息', 'verbose_name_plural': '管理员信息'},
        ),
        migrations.RenameField(
            model_name='user_admin',
            old_name='emial',
            new_name='email',
        ),
    ]
