# Generated by Django 2.2.4 on 2019-08-31 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190831_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='followedby',
            field=models.ManyToManyField(null=True, related_name='myfollows', to=settings.AUTH_USER_MODEL, verbose_name='谁的朋友'),
        ),
    ]
