# Generated by Django 3.0.2 on 2020-02-28 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200227_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(null=True, verbose_name='深造时间')),
                ('uvty_name', models.CharField(max_length=20, null=True, verbose_name='学校名称')),
                ('major', models.CharField(max_length=20, null=True, verbose_name='专业')),
                ('country', models.CharField(max_length=20, null=True, verbose_name='国家')),
                ('edu_degree', models.CharField(max_length=20, null=True, verbose_name='教育学历')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
        migrations.RenameField(
            model_name='jobexperience',
            old_name='job_period_start',
            new_name='employ_date',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job_city',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job_period_end',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job_place',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job_province',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='job_salary',
        ),
        migrations.RemoveField(
            model_name='user_profile_company',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='city',
            field=models.CharField(max_length=128, null=True, verbose_name='就业城市'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='company_name',
            field=models.CharField(max_length=128, null=True, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='country',
            field=models.CharField(max_length=128, null=True, verbose_name='就业国家'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='istop500',
            field=models.SmallIntegerField(null=True, verbose_name='公司是否为500强'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='job_name',
            field=models.CharField(max_length=128, null=True, verbose_name='职业名称'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='major_pro',
            field=models.SmallIntegerField(null=True, verbose_name='专业是否对口'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='province',
            field=models.CharField(max_length=128, null=True, verbose_name='就业省份'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='年薪'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='intro',
            field=models.CharField(max_length=300, null=True, verbose_name='公司简介'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='person_incharge_name',
            field=models.CharField(max_length=20, null=True, verbose_name='负责人名称'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='phonenum',
            field=models.CharField(max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='user_profile_company',
            name='province',
            field=models.CharField(max_length=30, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user_profile_company',
            name='identity',
            field=models.CharField(choices=[('1', '毕业生'), ('2', '在校生'), ('3', '企业账号'), ('4', '管理员')], default='3', max_length=20, verbose_name='用户身份'),
        ),
        migrations.AlterField(
            model_name='user_profile_company',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='公司名'),
        ),
        migrations.DeleteModel(
            name='EducationExperience',
        ),
    ]
