# Generated by Django 2.2.4 on 2019-08-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190828_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile_graduate',
            options={'verbose_name': '毕业生'},
        ),
    ]
