# Generated by Django 2.2.4 on 2019-08-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190828_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息表', 'verbose_name_plural': '消息表'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_graduate',
            options={'verbose_name': '毕业生信息', 'verbose_name_plural': '毕业生信息'},
        ),
    ]
