# Generated by Django 3.0.2 on 2020-02-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200228_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduexperience',
            options={'verbose_name': '深造经历', 'verbose_name_plural': '深造经历'},
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='com_type',
            field=models.CharField(choices=[('1', '各类企业'), ('2', '机关事业单位')], max_length=30, null=True, verbose_name='企业类型'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='field_type',
            field=models.CharField(choices=[('1', '教育'), ('2', '租赁和商务服务业'), ('3', '制造业'), ('4', '信息传输,软件和信息技术服务业')], max_length=30, null=True, verbose_name='就业行业'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='job_type',
            field=models.CharField(choices=[('1', '教育'), ('2', '租赁和商务服务业'), ('3', '制造业'), ('4', '信息传输,软件和信息技术服务业')], max_length=30, null=True, verbose_name='职业类型'),
        ),
        migrations.AddField(
            model_name='user_profile_graduate',
            name='edu_degree',
            field=models.CharField(choices=[('1', '本科'), ('2', '硕士'), ('3', '博士')], default='1', max_length=20, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='eduexperience',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='国家或地区'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='company_name',
            field=models.CharField(max_length=128, null=True, verbose_name='工作单位名称'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='月薪'),
        ),
    ]
