# Generated by Django 3.0.2 on 2020-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190831_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile_company',
            old_name='phonenum',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='user_profile_stu',
            old_name='birth_date',
            new_name='birth_data',
        ),
        migrations.RenameField(
            model_name='user_profile_stu',
            old_name='phonenum',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='education_background',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='honour',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='living_city',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='living_province',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='self_judgement',
        ),
        migrations.RemoveField(
            model_name='user_profile_graduate',
            name='university',
        ),
        migrations.AddField(
            model_name='user_profile_graduate',
            name='coin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile_graduate',
            name='gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='gpa总评'),
        ),
        migrations.AddField(
            model_name='user_profile_graduate',
            name='institute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user_profile_graduate',
            name='stunum',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user_profile_graduate',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='入校时间'),
        ),
        migrations.AlterField(
            model_name='user_profile_graduate',
            name='graduate_date',
            field=models.DateField(blank=True, null=True, verbose_name='毕业时间'),
        ),
    ]
