# Generated by Django 3.0.2 on 2020-01-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200126_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_stu',
            name='identity',
        ),
    ]
