# Generated by Django 2.2.4 on 2019-08-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190828_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='简历所在的路径')),
                ('name', models.CharField(max_length=50, verbose_name='简历的名字')),
                ('company', models.ManyToManyField(related_name='resumefromgraduate', to='user.User_Profile_Company', verbose_name='投递到的公司')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myresume', to='user.User_Profile_Graduate', verbose_name='毕业生的简历')),
            ],
            options={
                'verbose_name': '简历表',
                'verbose_name_plural': '简历表',
            },
        ),
    ]
